### ISSUE TITLE
HTML syntax issues

### ISSUE THREAD

**Issue by tjhorner** [ponydevs/MLPVC-RR#2]
See commit bef10a19331b95f089e56daa7d72462cff5c27ae for information

Quote from commit:

> I'm assuming there's some other problems like this around... it's fine in most modern browsers (Chrome, Firefox) but some (Safari, IE) just won't take the `attr=prop` syntax. Want me to go around fixing these?

**Comment by DJDavid98** [comment]
The values were left un-quoted because the quotes are optional according to the HTML specification, and I did not observe any site-breaking behaviour ever since I've been using them. Do you have any specific examples that result in the site breaking because of this?

Additionally, I do not wish to support any version of Internet Explorer below the latest version, which *(at the time of writing this)* is version 11. Having access to the site's usage statistics, I can safely ignore that browser family.

**Comment by SlvrEagle23** [comment]
I would think the best practice regarding this matter is to be consistent, and since some attributes _will_ require using quotes (i.e. multiple classes, CSS styles, etc) it is strongly recommended to use them for all attributes for consistency, even if the browser doesn't explicitly require it.

**Comment by DJDavid98** [comment]
Unless it causes trouble I'd like to stick to omitting them whenever possible to save keystrokes & a few bytes. If it turns out to be making the site unusable on a widely used browser and/or device, I'll add the quotes in.

**Comment by SlvrEagle23** [comment]
Well, not to be too terribly rude, but that's kind of dumb. The quotes exist for a reason, mainly to visually delineate the attribute names from their values, and to allow for expansion if necessary.

In any situation where you sacrifice readability for saving a few insignificant bytes of traffic or a few (often automated, depending on IDE) keystrokes, perhaps priorities should be re-evaluated.

I won't continue to argue the point, as I understand the developer mindset that caused this problem to begin with, but it's worth entertaining the idea that perhaps this _isn't_ the best way of doing this thing, and somebody offering to fix it in their own time isn't hurting you.

**Comment by tjhorner** [comment]
I agree with @SlvrEagle23, saving a few bytes will not make any significant difference. `attr="prop"` is the best (and recommended) way to do things. Just because something works doesn't make it good...

**Comment by tjhorner** [comment]
If you don't want to go through with this, it's fine. Just wanted to help :smile:

**Comment by DJDavid98** [comment]
I appreciate your initiative and the feedback from both of you, I don't see why it'd be good but nor do I see any reason why it could be bad. As stated in the readme I do not expect code contributions from others, and I'd have to re-minify the edited JS code myself either way, so I'll just do it myself.

**Comment by tjhorner** [comment]
> As stated in the readme I do not expect code contributions from others

Well you added that after this issue was created, but if you ask anyone else they will say that quoted attributes will be better. Unquoted attributes could go away any time and without any notice since it isn't the norm. It would also prevent you from using URL queries on anchors, which you would then quote but then it would be inconsistent!

But as I said, it's your choice.

**Comment by DJDavid98** [comment]
>Well you added that after this issue was created

[This commit](https://github.com/ponydevs/MLPVC-RR/commit/978b81db5c97a2b236463e1481fe9b3bab4f8113#diff-04c6e90faac2675aa89e2176d2eec7d8R31) happened a bit sooner :)

**Comment by tjhorner** [comment]
So why'd you make it open source if you weren't expecting contributions from others? Am confuse.

**Comment by SlvrEagle23** [comment]
All the benefit of looking good on a resume with none of the hassle of having to work with other people? ;)

**Comment by DJDavid98** [comment]
The reason is simple: To prove to the people I'm making the this site for that my intentions are not malicious.

**Comment by tjhorner** [comment]
That's a good point, but I don't think most people on MLP Vector Club will know how to differentiate malicious code from non-malicious code .-.

**Comment by DJDavid98** [comment]
Nonetheless, I feel less nervous knowing that I have nothing to hide from them.

**Comment by tjhorner** [comment]
Unrelated but why is the Ponies team a contributor again?

**Comment by DJDavid98** [comment]
It appears that I cannot push to the repository or change it's setting after removing it. I had to ask an org. admin to add it back for me.

**Comment by tjhorner** [comment]
ah right, since you're in that team as well.

**Comment by SeinopSys** [comment]
@tjhorner @SlvrEagle23 Looking back at this issue now I must say I owe you both an apology. This could have been handled a lot better and I deeply regret acting the way I did. I was frankly inexperienced and wasn't able to take constructive feedback and contributions for what it was. There's no excuse for what I did. I included your names in the projects's [readme](https://github.com/ponydevs/MLPVC-RR/blob/ae961d061907b77c4af19f9db271eefce9dd8dae/README.md#thanks-to) as a way to thank you for your help. If you would rather not be listed feel free to tell me, otherwise no further action is needed from your part.
